//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcON.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class garcONEntities : DbContext
    {
        public garcONEntities()
            : base("name=garcONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DOMINIO_FUNCAO> TB_DOMINIO_FUNCAO { get; set; }
        public virtual DbSet<TB_DOMINIO_TIPOPESSOA> TB_DOMINIO_TIPOPESSOA { get; set; }
        public virtual DbSet<TB_FUNCIONARIO> TB_FUNCIONARIO { get; set; }
        public virtual DbSet<TB_PESSOA> TB_PESSOA { get; set; }
        public virtual DbSet<TB_ENDERECO> TB_ENDERECO { get; set; }
        public virtual DbSet<TB_TELEFONE> TB_TELEFONE { get; set; }
    }
}
