//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DOMINIO_TIPOPESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DOMINIO_TIPOPESSOA()
        {
            this.TB_PESSOA = new HashSet<TB_PESSOA>();
        }
    
        public int TipoPessoaId { get; set; }
        public string DescricaoTipoPessoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PESSOA> TB_PESSOA { get; set; }
    }
}
