//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DOMINIO_FUNCAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DOMINIO_FUNCAO()
        {
            this.TB_FUNCIONARIO = new HashSet<TB_FUNCIONARIO>();
        }
    
        public int FuncaoId { get; set; }
        public string DescricaoFuncao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FUNCIONARIO> TB_FUNCIONARIO { get; set; }
    }
}
