//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FUNCIONARIO
    {
        public int FuncionarioId { get; set; }
        public int PessoaId { get; set; }
        public int FuncaoId { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
    
        public virtual TB_DOMINIO_FUNCAO TB_DOMINIO_FUNCAO { get; set; }
        public virtual TB_PESSOA TB_PESSOA { get; set; }
    }
}
