//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PESSOA()
        {
            this.TB_FUNCIONARIO = new HashSet<TB_FUNCIONARIO>();
            this.TB_ENDERECO = new HashSet<TB_ENDERECO>();
        }
    
        public int PessoaId { get; set; }
        public string Nome { get; set; }
        public string CPFCNPJ { get; set; }
        public string RG { get; set; }
        public int TipoPessoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FUNCIONARIO> TB_FUNCIONARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ENDERECO> TB_ENDERECO { get; set; }
        public virtual TB_TELEFONE TB_TELEFONE { get; set; }
        public virtual TB_DOMINIO_TIPOPESSOA TB_DOMINIO_TIPOPESSOA { get; set; }
    }
}
